apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
data:
  config.json: |-
    [
      {
        "clusterID": "9f1caa0b-78df-4788-b279-ca45e12686d9",
        "monitors": [
          "192.168.2.7:6789",
          "192.168.2.8:6789",
          "192.168.2.9:6789"
        ]
      }
    ]
